apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-sync-secrets
  namespace: gridgain
type: Opaque
stringData:
  SQLSERVER_CONN: "sqlserver://admin:admin@sqlserver-host:1433?database=testdb"
  GG_PASS: "admin"
